sudo: required
dist: trusty
language: node_js
node_js:
  - "4.5.0"
  - "6.9.5"

services:
  - postgresql

before_script:
  - psql -c 'create database documentos_test;' -U postgres
  - npm run db:migrate:test

script:
  - npm test

after_success:
  - npm run coveralls

addons:
  postgresql: "9.3"

after_failure:
  - npm run coveralls
