export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_DOC_SUCCESS = 'CREATE_DOC_SUCCESS';
export const LOAD_DOCS_SUCCESS = 'LOAD_DOCS_SUCCESS';
export const GET_DOCUMENT = 'GET_DOCUMENT';
